{
  "CompileError": {
    "module": "test_invalid_try_catch2.np",
    "errors": [
      {
        "message": "Expect catch after try block at token try",
        "line": 5
      },
      {
        "message": "Expect identifier after catch at end",
        "line": 7
      }
    ]
  }
}